sudo: false
language: java
cache:
  directories:
  - "$HOME/.m2"
jdk: oraclejdk8
env:
  matrix:
  - DISPLAY=:99.0
  global:
    secure: "ewwqSQJ06U17QkraXAwdhyoWL8tupkr04qAwQtZ2n3sF2Em6JbZAGP+XX5T+GIvaGkxZ7pBGwPvQWyfRcH9+EwjH+Zblph358iAGyQghllUKHaluexXqYMvWOqu/HETUa0EBQlnCgKweOvLiMq8oBX9UEFI7Wk0cKfg97LR81BQ8BKjN3BWoKpDQAcBMYsaJI2YP3ef5Ak/rmmSCiTEiTwGWUK6nc0micDv3GLN6UgtanziojtEaxlGTk1tRF8wHinCvz+/MDGmrmteo4AeBLu2dlfepZj5+86qZKwD3TErbsePODh/D4tktb5M9yRDRfSk6WZz8XKDL807BZw7Buq+81AGlp6QtazEAGg6E61ROna3B7goCuQL6HJeCnTZRXwyh1lnbgCG7T7O+8VUNizGAR6NKlmVJu/TUzqj/2W6Z1OAlaxFMGsJaFdx4VmVUb8PLgMpPxzelP1pik8w0Nxam1Ri8HK/vI7aSuWVlt4MpgVXlLjOKVmGG9nytKcEPuSbouKbMWeS2/tomvixH/f2bR3vC0BlM9P0edJsL7uhL3dZbxFfUz8+4uOYmUX7bBeu3tjWebp3hY6MaB61feFQevi6CRa8DmGXkfe3ww7NEPuIaNQzp3ONJOlE9AIh9h8i3MEVfyNEwHXtCYldWDvZzxUZBJQmFbof6h9W/dP4="
addons:
  apt:
    packages:
    - metacity
before_install:
- export DISPLAY=:99.0
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
- sleep 5
- metacity --sm-disable --replace 2> metacity.err &
script:
- mvn clean package
- mvn clean install -P stable
- mvn clean install -P preview
- mvn clean install -P experimental